/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parchisb59226.vista;

import com.mycompany.parchisb59226.controlador.ControladorPrincipal;

/**
 *
 * @author Joselyn Ledezma V
 */
public class GUICreditos extends javax.swing.JFrame {
    
    /**
     * Creates new form GUICreditos
     */
    public GUICreditos(ControladorPrincipal controlador) {
        initComponents();
        escuchar(controlador);
    }
    public void escuchar(ControladorPrincipal controlador){
    btnAtras.addActionListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        jlFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Desarrollado por: Joselyn Ledezma - Yuliana Masis");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 190, 500, -1));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonAtras.png"))); // NOI18N
        btnAtras.setActionCommand("atrasCreditos");
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 590, -1, -1));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tableroCreditos.png"))); // NOI18N
        getContentPane().add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlFondo;
    // End of variables declaration//GEN-END:variables
}
