/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parchisb59226.vista;

import com.mycompany.parchisb59226.controlador.ControladorPrincipal;

/**
 *
 * @author Joselyn Ledezma V
 */
public class GUIHistoria extends javax.swing.JFrame {
    
   
    /**
     * Creates new form GUIHistoria
     * @param controlador
     */
    public GUIHistoria(ControladorPrincipal controlador) {
        initComponents();
        escuchar(controlador);
    }
     public void escuchar(ControladorPrincipal controlador){
    btnAtrasHistoria.addActionListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAtrasHistoria = new javax.swing.JButton();
        jlFondoHistoria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Historia del juego:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        btnAtrasHistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonAtras.png"))); // NOI18N
        btnAtrasHistoria.setActionCommand("AtrasHistoria");
        btnAtrasHistoria.setBorderPainted(false);
        btnAtrasHistoria.setContentAreaFilled(false);
        getContentPane().add(btnAtrasHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 640, -1, -1));

        jlFondoHistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tableroHistoria.png"))); // NOI18N
        getContentPane().add(jlFondoHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 950, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasHistoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlFondoHistoria;
    // End of variables declaration//GEN-END:variables
}
