/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parchisb59226.vista;

import com.mycompany.parchisb59226.controlador.ControladorPrincipal;

/**
 *
 * @author Joselyn Ledezma V
 */
public class GUIInstrucciones extends javax.swing.JFrame {
    
  
    /**
     * Creates new form GUIInstrucciones
     * @param controlador
     */
    public GUIInstrucciones(ControladorPrincipal controlador) {
        initComponents();
        escuchar(controlador);
       
    }
    
  
    public void escuchar(ControladorPrincipal controlador){
    btnAtrasInstrucciones.addActionListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtrasInstrucciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlFondoInstrucciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtrasInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonAtras.png"))); // NOI18N
        btnAtrasInstrucciones.setActionCommand("AtrasInstrucciones");
        btnAtrasInstrucciones.setBorderPainted(false);
        btnAtrasInstrucciones.setContentAreaFilled(false);
        getContentPane().add(btnAtrasInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 590, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Instrucciones: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        jlFondoInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tableroInstrucciones.png"))); // NOI18N
        getContentPane().add(jlFondoInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasInstrucciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlFondoInstrucciones;
    // End of variables declaration//GEN-END:variables
}
