/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parchisb59226.vista;

import com.mycompany.parchisb59226.controlador.ControladorJuego;
import com.mycompany.parchisb59226.controlador.ControladorPrincipal;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Joselyn Ledezma V
 */
public class GUIJugador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIJugador.class.getName());

    /**
     * Creates new form GUIJugador
     */
    public GUIJugador(ControladorPrincipal controlador) {
        initComponents();
        btnContinuar.addActionListener(controlador);
    }

    public String getCbColor() {
        return (String) cbColor.getSelectedItem().toString();
    }

    public String getTxtJugador1() {
        return txtJugador1.getText();
    }

    public String getTxtJugador2() {
        return txtJugador2.getText();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtJugador1 = new javax.swing.JTextField();
        txtJugador2 = new javax.swing.JTextField();
        cbColor = new javax.swing.JComboBox<>();
        btnContinuar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtJugador1.setColumns(20);
        txtJugador1.setToolTipText("");
        getContentPane().add(txtJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 270, 50));

        txtJugador2.setColumns(20);
        getContentPane().add(txtJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 270, 50));

        cbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------", "Amarillo", "Rojo", "Azul", "Verde" }));
        getContentPane().add(cbColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        btnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonContinuar.png"))); // NOI18N
        btnContinuar.setActionCommand("Continuar");
        btnContinuar.setContentAreaFilled(false);
        getContentPane().add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPersonaje.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 880, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JComboBox<String> cbColor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtJugador1;
    private javax.swing.JTextField txtJugador2;
    // End of variables declaration//GEN-END:variables
}
