/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parchisb59226.vista;

import com.mycompany.parchisb59226.controlador.ControladorJuego;

/**
 *
 * @author Joselyn Ledezma V
 */
public class GUIJuego extends javax.swing.JFrame {
    
    /**
     * Creates new form GUIJuego
     */
    public GUIJuego(ControladorJuego controlador) {
        initComponents();
        panelJuego.escuchar(controlador);
        panelControl.escuchar(controlador);
    }

    public PanelControl getPanelControl() {
        return panelControl;
    }

    public PanelJuego getPanelJuego() {
        return panelJuego;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJuego = new com.mycompany.parchisb59226.vista.PanelJuego();
        panelControl = new com.mycompany.parchisb59226.vista.PanelControl();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelJuego.setOpaque(false);

        javax.swing.GroupLayout panelJuegoLayout = new javax.swing.GroupLayout(panelJuego);
        panelJuego.setLayout(panelJuegoLayout);
        panelJuegoLayout.setHorizontalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        panelJuegoLayout.setVerticalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        getContentPane().add(panelJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 590, 610));
        getContentPane().add(panelControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -10, -1, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.parchisb59226.vista.PanelControl panelControl;
    private com.mycompany.parchisb59226.vista.PanelJuego panelJuego;
    // End of variables declaration//GEN-END:variables
}
