/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parchisb59226.vista;

import com.mycompany.parchisb59226.controlador.ControladorPrincipal;

/**
 *
 * @author Joselyn Ledezma V
 */
public class GUIPrincipal extends javax.swing.JFrame {
    
    

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal(ControladorPrincipal controlador) {
        initComponents();
        escuchar(controlador);
    }
public void escuchar(ControladorPrincipal controlador){
btnJugar.addActionListener(controlador);
btnCreditos.addActionListener(controlador);
btnHistoria.addActionListener(controlador);
btnInstrucciones.addActionListener(controlador);
btnSalir.addActionListener(controlador);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInstrucciones = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        btnHistoria = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jlFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/instruccionesPrincipal.png"))); // NOI18N
        btnInstrucciones.setActionCommand("Instrucciones");
        btnInstrucciones.setBorderPainted(false);
        btnInstrucciones.setContentAreaFilled(false);
        getContentPane().add(btnInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/jugarPrincipal.png"))); // NOI18N
        btnJugar.setActionCommand("Jugar");
        btnJugar.setBorderPainted(false);
        btnJugar.setContentAreaFilled(false);
        getContentPane().add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 770, -1));

        btnCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/creditosPrincipal.png"))); // NOI18N
        btnCreditos.setActionCommand("Creditos");
        btnCreditos.setBorderPainted(false);
        btnCreditos.setContentAreaFilled(false);
        btnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));

        btnHistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/historiaPrincipal.png"))); // NOI18N
        btnHistoria.setToolTipText("");
        btnHistoria.setActionCommand("Historia");
        btnHistoria.setBorderPainted(false);
        btnHistoria.setContentAreaFilled(false);
        getContentPane().add(btnHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, -1, 80));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonSalir.png"))); // NOI18N
        btnSalir.setActionCommand("Salir");
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 570, -1, -1));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal.png"))); // NOI18N
        getContentPane().add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreditosActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnHistoria;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jlFondo;
    // End of variables declaration//GEN-END:variables
}
