/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.parchisb59226.vista;

import com.mycompany.parchisb59226.controlador.ControladorJuego;
import javax.swing.JLabel;

/**
 *
 * @author Joselyn Ledezma V
 */
public class PanelControl extends javax.swing.JPanel {

    /**
     * Creates new form PanelControl
     */
    public PanelControl() {
        initComponents();
    }
    public void escuchar(ControladorJuego controlador){
        btnAtras.addActionListener(controlador);
        btnDado.addActionListener(controlador);
    }

    public void setJlNombreJugador1(String jlNombreJugador1) {
        this.jlNombreJugador1.setText(jlNombreJugador1);
    }

    public void setJlNombreJugador2(String jlNombreJugador2) {
        this.jlNombreJugador2.setText(jlNombreJugador2);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDado = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jlNombreJugador1 = new javax.swing.JLabel();
        jlNombreJugador2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDado.setText("Dado");
        add(btnDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, -1, -1));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonAtras.png"))); // NOI18N
        btnAtras.setActionCommand("atras");
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 640, -1, -1));

        jlNombreJugador1.setText("Jugador 1");
        add(jlNombreJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, -1, -1));

        jlNombreJugador2.setText("Jugador 2 ");
        add(jlNombreJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TableroFondo_1.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1030, 700));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnDado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlNombreJugador1;
    private javax.swing.JLabel jlNombreJugador2;
    // End of variables declaration//GEN-END:variables
}
